export const videosActions = {
    FETCH_VIDEOS_START : 'FETCH_VIDEOS_START',
    FETCH_VIDEOS_SUCCESS: 'FETCH_VIDEOS_SUCCESS',
    FETCH_VIDEOS_FAILURE: 'FETCH_VIDEOS_FAILURE',
    SET_ACTIVE_VIDEO: 'SET_ACTIVE_VIDEO'
}